services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env.test
 
  node:
    image: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres  
    env_file:
      - ./back-end/.env.test
