on:
  push:
    branches:
      - main
name: AWS Build and Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          PORT: 4000
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DATABASE: passgen_test
          DATABASE_URL: postgresql://postgres:1234@postgres:5432/passgen_test?schema=public
          directory: back-end/
          file_name: .env.test
