on:
  push:
    branches:
      - master
name: AWS Build and Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          envkey_PORT: ${{secrets.PORT}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          directory: back-end
          file_name: .env
          fail_on_empty: true

      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_APP_BACKEND_URL: ${{secrets.VITE_APP_BACKEND_URL}}
          directory: front-end
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: docker compose build

      - name: Run
        run: docker compose down && docker compose up -d
