name: CI validation
on: [pull_request]
jobs:
  Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Create a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          PORT: ${{secrets.PORT}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          envkey_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          envkey_POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: back-end/
          file_name: .env.test

      - name: Run tests
        run: docker compose -f docker-compose-test.yml run node npm run test
